version: '3'
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www

  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "docker_user"
      POSTGRES_PASSWORD: "docker_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
