version: '3'
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www
